// react-lifting-state-up/src/components/AddTodo.tsx
import { ChangeEvent, useState } from "react";
import { Todo } from "../models/Todo";

interface IAddTodoProps {
  saveTodo(newTodo: Todo): void;
}

export const AddTodo = (props: IAddTodoProps) => {
  const [todoText, setTodoText] = useState("");

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setTodoText(e.target.value);
  };

  const handleClick = () => {
    let todo = new Todo(todoText);
    props.saveTodo(todo);
    setTodoText("");
  };

  return (
    <div>
      <input type="text" onChange={handleChange} value={todoText} />
      <button type="button" onClick={handleClick}>
        Spara
      </button>
    </div>
  );
};

// angular-directive/src/app/components/addtodo/addtodo.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-addtodo',
  templateUrl: './addtodo.component.html',
  styleUrls: ['./addtodo.component.scss'],
})
export class AddtodoComponent implements OnInit {
  @Output() saveTodo = new EventEmitter<string>();
  todoText: string = '';

  constructor() {}

  ngOnInit(): void {}

  handleChange(todo: string) {
    this.todoText = todo;
  }

  save() {
    this.saveTodo.emit(this.todoText);
  }
}

<div>
    <input type="text" #todo (keyup)="handleChange(todo.value)" />
    <button (click)="save()">Spara</button>
</div>
