// angular-componentconversation/src/app/components/addtodo/addtodo.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from 'src/app/models/Todo';
import { TodosService } from 'src/app/services/todos.service';

@Component({
  selector: 'app-addtodo',
  templateUrl: './addtodo.component.html',
  styleUrls: ['./addtodo.component.scss'],
})
export class AddtodoComponent implements OnInit {
  todoText: string = '';

  constructor(private service: TodosService) {}

  ngOnInit(): void {}

  handleChange(valueFromUser: string) {
    this.todoText = valueFromUser;
  }

  save() {
    let newTodo: Todo = new Todo(this.todoText);
    this.service.addTodo(newTodo);
  }
}

<div>
    <input type="text" #newTodo (keyup)="handleChange(newTodo.value)" />
    <button (click)="save(); newTodo.value=''">Spara</button>
</div>

// react-lifting-state-up/src/components/AddTodo.tsx
import { ChangeEvent, useState } from "react";
import { Todo } from "../models/Todo";

interface IAddTodoProps {
  saveTodo(newTodo: Todo): void;
}

export const AddTodo = (props: IAddTodoProps) => {
  const [todoText, setTodoText] = useState("");

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setTodoText(e.target.value);
  };

  const handleClick = () => {
    let todo = new Todo(todoText);
    props.saveTodo(todo);
    setTodoText("");
  };

  return (
    <div>
      <input type="text" onChange={handleChange} value={todoText} />
      <button type="button" onClick={handleClick}>
        Spara
      </button>
    </div>
  );
};
